=== OpenKnowledgeMaps/Headstart/doc/json-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "relation": {
        "type": "string"
      },
      "identifier": {
        "type": "string"
      },
      "title": {
        "type": "string"
      },
      "paper_abstract": {
        "type": "string"
      },
      "published_in": {
        "type": "string"
      },
      "year": {
        "type": "string",
        "format": "date"
      },
      "subject_orig": {
        "type": "string"
      },
      "subject": {
        "type": "string"
      },
      "authors": {
        "type": "string"
      },
      "link": {
        "type": "string"
      },
      "oa_state": {
        "type": "string",
        "enum": ["0", "1", "2", "3", "4", "5"]
      },
      "url": {
        "type": "string"
      },
      "relevance": {
        "type": "integer",
        "minimum": 0,
        "maximum": 100
      },
      "lang_detected": {
        "type": "string"
      },
      "cluster_labels": {
        "type": "string"
      },
      "x": {
        "type": "string"
      },
      "y": {
        "type": "string"
      },
      "area_uri": {
        "type": "integer",
        "minimum": 0,
        "maximum": 4
      },
      "area": {
        "type": "string"
      }
    },
    "required": [
      "id",
      "relation",
      "identifier",
      "title",
      "paper_abstract",
      "year",
      "subject_orig",
      "subject",
      "authors",
      "link",
      "oa_state",
      "url",
      "relevance",
      "lang_detected",
      "cluster_labels",
      "x",
      "y",
      "area_uri",
      "area"
    ]
  }
}

=== OpenKnowledgeMaps/Headstart/examples/tome.gg/docs/example.json
{
  "id": "001a8aa44f55f1d133d4ed2b0e7b4a1e4125901c84d5086b9648dded9251ed1c",
  "relation": "doi:10.1080/18377122.2016.1222238; issn:1837-7122; issn:1837-7130; orcid:https://orcid.org/0000-0002-2888-4974; orcid:https://orcid.org/0000-0001-7206-4781",
  "identifier": "https://espace.library.uq.edu.au/view/UQ:403365",
  "title": "Computer says no: an analysis of three digital food education resources",
  "paper_abstract": "What kind of thing will food education become in digitisedclassrooms? Drawn from a broader research project concernedwith the\\u2018e turn\\u2019in school health and physical education, thispaper analyses three examples of digital food education (DEF).This is done by considering the role of digital technology inchanging\\u2013or not changing\\u2013earlier forms of food education. Ineach case, these processes are viewed as portals of connectionthrough which knowledge claims are produced, copied, merged,manipulated, juxtaposed and re-represented. Food education is,therefore, conceptualised not as the distillation of scientificknowledge, but as the uses to which this knowledge can be put.Our overall finding\\u2013that in many ways DEF is not very differentfrom that which preceded it\\u2013echoes other scholars; nutritionismdressed in digital garb is still nutritionism. However, rather thanarguing that DEF needs to adhere more faithfully to nutritionalscience, we argue the reverse; that digital technology has the as yetunmet potential to move food education away from nutritionalscience towards something more intellectually rich and educationallyengaging",
  "published_in": "",
  "year": "2016-08-26",
  "subject_orig": "Digital games; Digital food education; Digitised classrooms; Health and physical education; Actor network theory; 2732 Orthopedics and Sports Medicine; 3304 Education; 3612 Physical Therapy; Sports Therapy and Rehabilitation",
  "subject": "Digital games; Digital food education; Digitised classrooms; Health and physical education; Actor network theory;    Sports Therapy and Rehabilitation",
  "authors": "Gard, Michael; Enright, Eimear",
  "link": "https://espace.library.uq.edu.au/view/UQ: 403365",
  "oa_state": "2",
  "url": "001a8aa44f55f1d133d4ed2b0e7b4a1e4125901c84d5086b9648dded9251ed1c",
  "relevance": 51,
  "lang_detected": "english",
  "cluster_labels": "Decision support, Digital food education, Education revolution",
  "x": "0.0336057408338733",
  "y": "-0.016385020362244",
  "area_uri": 3,
  "area": "Decision support, Digital food education, Education revolution"
}
